spring:
  main:
    show-banner: false
  profiles:
    active: development
  mail:
    properties:
      mail.smtp.from: bricolage@ce-ds-sections.fr
  data:
    rest:
      base-path: /api
  jpa:
    properties:
      hibernate:
          default:
            directory_provider: filesystem
            indexBase: /tmp/diy/lucene/indexes/
          users:
            directory_provider: ram
          tools:
            directory_provider: ram
          categories:
            directory_provider: ram
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    serialization-inclusion: NON_NULL

security:
  enable-csrf: false

# Application configuration
app:
  email:
    subject: Section Bricolage
    registration:
      tokenExpiryTime: 3600

---

spring:
  profiles: development
  jackson:
    serialization:
      indent_output: true
  datasource:
    data: classpath:/sql/import-*.sql
  mail:
    host: smtp.paris.exalead.com

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

security:
  basic:
    enabled: false

search:
  index:
    build-startup: true

---

spring:
    profiles: production
    main:
      show-banner: false
    jpa:
      show-sql: false
      properties:
        hibernate:
          search:
            generate_statistics: true
    # only keep remote restart/debugging
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: false

server:
    port: 9001

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data.rest: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
