spring:
  profiles:
    active: development
  main:
    show-banner: false
  data:
    rest:
      base-uri: /api
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

security:
  enable-csrf: false

---

spring:
  profiles: development
  jackson:
    serialization:
      indent_output: true
  datasource:
    data: classpath:/sql/import-*.sql
  jpa:
    properties:
      hibernate:
        search:
          generate_statistics: true
          default:
            directory_provider: filesystem
            indexBase: /tmp/diy/lucene/indexes/
          users:
            directory_provider: ram
          tools:
            directory_provider: ram
          categories:
            directory_provider: ram

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

security:
  basic:
    enabled: false

---

spring:
    profiles: production
    jpa:
      show-sql: false
      properties:
        hibernate:
          search:
            generate_statistics: true

server:
    port: 9001

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data.rest: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR

