spring:
  main:
    show-banner: false
  profiles:
    active: development
  mail:
    properties:
      mail.smtp.from: bricolage@ce-ds-sections.fr
  data:
    rest:
      base-path: /api
  datasource:
    data: classpath:/sql/import-*.sql
  jpa:
    properties:
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default:
          directory_provider: filesystem
          indexBase: /tmp/diy/lucene/indexes/
        users:
          directory_provider: ram
        tools:
          directory_provider: ram
        categories:
          directory_provider: ram
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    serialization-inclusion: NON_NULL
  freemarker:
    enabled: false # disable view resolver

security:
  enable-csrf: false

# Application configuration
app:
  email:
    registration:
      subject: Activation de votre compte à la section bricolage
      tokenExpiryTime: 3600

---

spring:
  profiles: development
  jackson:
    serialization:
      indent_output: true
  mail:
    host: smtp.paris.exalead.com
  freemarker:
    cache: false
  jpa:
    database: H2

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO

security:
  basic:
    enabled: false

search:
  index:
    build-startup: true

---

spring:
    profiles: production
    main:
      show-banner: false
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      properties:
          search:
            generate_statistics: true
    datasource:
      url: jdbc:mysql://localhost:3306/diy_db
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
    # TODO change smtp host
    mail:
      host: smtp.paris.exalead.com
    # only keep remote restart/debugging
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: false

server:
    port: 9001

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data.rest: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
