spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api
  jpa:
    properties:
      hibernate:
          default:
            directory_provider: filesystem
            indexBase: /tmp/diy/lucene/indexes/
          users:
            directory_provider: ram
          tools:
            directory_provider: ram
          categories:
            directory_provider: ram
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    serialization-inclusion: NON_NULL

security:
  enable-csrf: false

search:
  index:
    build-startup: false

---

spring:
  profiles: development
  jackson:
    serialization:
      indent_output: true
  datasource:
    data: classpath:/sql/import-*.sql

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

security:
  basic:
    enabled: false

---

spring:
    profiles: production
    main:
      show-banner: false
    jpa:
      show-sql: false
      properties:
        hibernate:
          search:
            generate_statistics: true
    # only keep remote restart/debugging
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: false

server:
    port: 9001

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data.rest: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR

