spring:
  main:
    banner-mode: off
  profiles:
    active: development
  mail:
    properties:
      mail.smtp.from: bricolage@ce-ds-sections.fr
  data:
    rest:
      base-path: /api
  datasource:
    data: classpath:/sql/import-*.sql
  jpa:
    properties:
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default:
          directory_provider: filesystem
          indexBase: /tmp/diy/lucene/indexes/
        users:
          directory_provider: ram
        tools:
          directory_provider: ram
        categories:
          directory_provider: ram
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    default-property-inclusion: non_null

security:
  enable-csrf: false

# Application configuration
app:
  email:
    registration:
      subject: Activation de votre compte à la section bricolage
      token-expiration: 3600

---

spring:
  profiles: development
  jackson:
    serialization:
      indent_output: true
  # TODO change smtp host
  mail:
    host: smtp.paris.exalead.com
  freemarker:
    cache: false
  h2:
    console:
      enabled: true


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO

security:
  basic:
    enabled: false

search:
  index:
    build-startup: false

---


spring:
    profiles: production
    jpa:
      show-sql: false
      hibernate:
#        ddl-auto: create-drop
        ddl-auto: validate
      properties:
          search:
            generate_statistics: true
    datasource:
      url: jdbc:mysql://db:${DB_PORT_3306_TCP_PORT}/${DB_ENV_DB_NAME}
      driver-class-name: com.mysql.jdbc.Driver
      username: ${DB_ENV_DB_USER}
      password: ${DB_ENV_DB_PASS}
    # TODO change smtp host
    mail:
      host: smtp.paris.exalead.com
    # only keep remote restart/debugging
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: false

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data.rest: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
